### ISSUE TITLE
Any plans for adding this tool to Homebrew?

### ISSUE THREAD

**Issue by mihaiconstantin** [actuallymentor/battery#1]
Thanks for this super handy tool! 
Have you considered adding it to Homebrew? 
Also, is there an uninstall script? Or at least the steps one would need to follow?

**Comment by actuallymentor** [comment]
@mihaiconstantin  You have docs that describe how to submit tools with a setup scrip that requires superuser permissions?

**Comment by mihaiconstantin** [comment]
@actuallymentor No, I don't have any info on that.

@JacksonChen666 I think your suggestion seems more reasonable.

**Comment by Pyciko** [comment]
Just wanna say thank you fellow person for releasing this. AlDente with its 30$ lifetime (or 15$ per year) pro version just to hide the ****ing menubar icon is insane...

**Comment by actuallymentor** [comment]
@mihaiconstantin you can now install this as a cask: `brew install battery`. It installs the GUI app which in the background installs the CLI.

Please let me know if it works for you, I have no fresh device to test it on.

Ps. @pyciko you're welcome

**Comment by pyciko** [comment]
worked like charm!

**Comment by mihaiconstantin** [comment]
@actuallymentor, it works brilliantly! Awesome job!
