### ISSUE TITLE
Top-up feature

### ISSUE THREAD

**Issue by rusho** [actuallymentor/battery#10]
Hi, I wonder if it would be possible to have an ability to top-up (charge to 100%), but still keep the original maintenance setting. Currently, if I set `battery maintain 80` and before business trip I do `battery charge 100`, it removes the 80% maintenance level. It'd be ideal if that maintenance level is kept, so that I don't forget about it.

**Comment by actuallymentor** [comment]
This can be achieved with bash:

```
battery charge 100 && battery maintain 80
```

The second happens after the first.
