### ISSUE TITLE
External display not working when charge limit is enabled 

### ISSUE THREAD

**Issue by n3w6i3** [actuallymentor/battery#100]
Since updating the app yesterday I noticed that my external display (connected via usb-c thunderbolt 3) is not working when my mac is in clamshell mode and i have charging limited to default 80% (and battery is full). Worth noting that I am using GUI and not CLI, but since this issue is persisting I tried playing with CLI commands and no luck in solving the problem. 

It makes sense that if the battery is not charing and if a macbook is closed that the display is off, but I had no problems using the app this way till now and would be very grateful to getting a workaround as I prefer just one cable connected to my mac. 

Kind regards

**Comment by gekoxyz** [comment]
I have the same problem, except i have the external display connected via HDMI. I have 86% battery but the status is "Power Source: Battery". I'm also using the GUI

**Comment by sunneydev** [comment]
Once it discharges it works just fine.

**Comment by actuallymentor** [comment]
Clamshell users, please try [this beta release](https://github.com/actuallymentor/battery/releases/tag/v1.1.4-beta) and thumbs up/down it to let me know if it works for you now!

There is now a new GUI option:

![image](https://user-images.githubusercontent.com/9071382/224797809-13dedd79-ac9e-46cb-bf77-235fb8a28da9.png)

**Comment by n3w6i3** [comment]
Just tried the update, unfortunately does not work for me in clamshel,  even when force discharging is enabled and battery is full.

**Comment by actuallymentor** [comment]
@n3w6i3 you're supposed to have it disabled :)

**Comment by actuallymentor** [comment]
Closed by release [v1.1.4](https://github.com/actuallymentor/battery/releases/tag/v1.1.4). Please reopen if you have the same issue with that release (with debug info).
