### ISSUE TITLE
Menu Bar Icon without battery indicator

### ISSUE THREAD

**Issue by 2bsc** [actuallymentor/battery#102]
Thanks a lot for your contribution.

I would like to suggest an option to choose a static icon for the Menu Bar instead, as I would like to keep the original macOS battery indicator (e.g. for high usage apps), but having two batteries (one landscape, one vertical) is kinda weird. Having a symbol simply indicating 80%-limiter On / Off would be a great addition.

Best regards
Carl

**Comment by jakjakob** [comment]
You could just install the CLI version, if you don't mind using only the terminal

**Comment by 2bsc** [comment]
That's for sure a simple solution, but I may want to quickly change things or see the current status, where the CLI in the end is much less convenient then a small indicator in the menu bar. And although I might be comfortable (to some degree) using the Terminal at times, this probably doesn't work for all users.

It's simply a would-be-nice-to-have feature :)
