### ISSUE TITLE
Check input type for charge and charging commands to prevent confusion

### ISSUE THREAD

**Issue by lodewijkvankeizerswaard** [actuallymentor/battery#104]
I sometimes mix up the difference between the `charge` and `charging` commands, which results in confusion and time loss. I think this is easily solvable by adding warnings or errors on wrong input types, i.e. strings for `charge` and integers for `charging`. This might also help new users, or users that are less familiar with the English language.

I am willing to create a quick pull request that adds type checks to these two commands.

Additional info:
When entering the non-sensical command `sudo battery charge off`, the output is not very helpful:

<img width="640" alt="image" src="https://user-images.githubusercontent.com/22987218/224009973-bf87fc75-d298-4c63-9a82-aae2aecb70f9.png">

**Comment by actuallymentor** [comment]
Sounds good to me, are you comfortable with creating a PR?
