### ISSUE TITLE
when enabled battery limit and ac adapter and external monitor connected, mac go sleeping when lid closed

### ISSUE THREAD

**Issue by epaxpax** [actuallymentor/battery#106]
![Screenshot 2023-03-11 at 21 35 40](https://user-images.githubusercontent.com/23380293/224510460-1610fc84-be23-4d15-b46a-1de86ff87fa1.png)

**Comment by epaxpax** [comment]
![image](https://user-images.githubusercontent.com/23380293/224510560-05a67ae8-e368-4843-b46b-1878d47a0c9c.png)

**Comment by actuallymentor** [comment]
Closed by release [v1.1.4](https://github.com/actuallymentor/battery/releases/tag/v1.1.4). Please reopen if you have the same issue with that release (with debug info).

**Comment by epaxpax** [comment]
thx, working
