### ISSUE TITLE
Set charge level in GUI Tool

### ISSUE THREAD

**Issue by PatiB87** [actuallymentor/battery#108]
Hey,

I really love the tool but I have to use the CLI tool to set the percentage to charge to. Often I set it down to 50-60 when I know that I use the Mac docked for like a week.
But sometimes the GUI tool does reset this to 80%. Didn't find out when exactly.
Could you put an extra option in the GUI tool to change the desired percentage?

**Comment by ballo** [comment]
I avoid using the GUI tool for this reason

**Comment by actuallymentor** [comment]
I am purposefully keeping the GUI as simple as possible. Advanced users are encouraged to use the CLI

**Comment by ballo** [comment]
Yeah, except that if you reboot you have to manually run the CLI exec
