### ISSUE TITLE
Is there a way to stop my phone charging while connected to my macbook through type c cable?

### ISSUE THREAD

**Issue by Naim995** [actuallymentor/battery#116]
Perhaps this is not a question for here, but I will make it anyway. Maybe this would serve as a suggestion to add this feature in the future.
I am software engineer and I run tests on my mobile devices. However, I don't want my mobile devices to suck the battery out of my macbook so I was wondering if turning this off was even possible ?

I heard there are some data only cables but I didn't have any luck finding one

**Comment by Anatharias** [comment]
This would be awesome, but would require the same kind of SMC driver on the iPhone to prevent the charge.

**Comment by amazonsingh** [comment]
maybe connect your iphone to xcode using wifi debugging

**Comment by actuallymentor** [comment]
Unknown. Let me know if you figure out how to do this.
