### ISSUE TITLE
Battery limiter error: Cannot read properties of undefined (reading 'includes')

### ISSUE THREAD

**Issue by jimdoc** [actuallymentor/battery#118]
Error message:
Battery limiter error: Cannot read properties of undefined (reading 'includes')

This error message has appeared once before.

battery.log actually contains no entries from today.

<img width="363" alt="image" src="https://user-images.githubusercontent.com/2263128/226076922-7fefe528-1aad-4cbb-b5c1-06481db47721.png">

After closing error message, "Enable 80% battery limit" is checked.

Just passing along an error that occurred.
Let me know if any additional info is needed.

**Comment by actuallymentor** [comment]
Use issue template please
