### ISSUE TITLE
Installation caused noticeable connection delay between MBP M1 and Mac Studio external display

### ISSUE THREAD

**Issue by lyubomirg1995** [actuallymentor/battery#120]
Issue:

I unplugged the thunderbolt cable from my MacBook Pro M1, plugged it back in, and noticed almost a 10 second delay before my computer's data was transferred over to my external monitor. Before that, it was almost immediate. For example, when audio was playing on my laptop, and I plugged in my computer to the external display, the audio would be immediately interrupted and played on my external display. Now, the screen takes 3 seconds to appear, while the audio would play on my laptop for a few seconds, before it finally gets registered by my display. 

Attempts to resolve:

I uninstalled the application from the menu bar. Nothing changed. I decided to reinstall the application again because I figured I'd need my laptop to stop charging at maximum capacity while plugged into my external display to avoid damaging the battery. The setting to force discharge immediately activated, whereas before I had to enable it manually upon first installation. Whatever changes were made to internal files, they were not undone with an uninstallation. I noticed many of the app's contents remained when I went to the application, then right-clicked on it to show package contents. How can I restore my computer to its previous state before scripts were installed to change my computer's settings? A simple uninstall of the application does not seem enough. I want to restore my external display's previous responsiveness to my Macbook Pro. 

Thank you.

**Comment by actuallymentor** [comment]
Please use the issue template.
