### ISSUE TITLE
Charge limit not working. 

### ISSUE THREAD

**Issue by dohran** [actuallymentor/battery#124]
Hello,
I've installed Battery twice. First with the .dmg file, it did not work so I uninstalled it using the button under 'About V.1.1.4. 
The second time is by launching the app directly from the .zip file but it's still not working unfortunately. 
Can you help?
I'm on a M1 MacBook Air. 

<img width="299" alt="Capture d’écran 2023-04-04 à 14 33 23" src="https://user-images.githubusercontent.com/129444860/229765784-c1f71339-021b-4beb-9e3d-2b53840f0a0b.png">

**Comment by actuallymentor** [comment]
Use the issue template please.
