### ISSUE TITLE
Implement ability to hide app from menu bar

### ISSUE THREAD

**Issue by la1440** [actuallymentor/battery#131]
My menu bar is clogged, and I also see no reason why I should have two battery icons in my menu bar at once. I was wondering if it would be possible to implement a "hide from menu bar" button that makes it so that, you launch the app via Finder or Spotlight or whatever you fancy, it briefly shows up in the menu bar, and after a few seconds of inactivity, it hides away again. Bartender broke my system for god-knows-what-reason, and none of the other menu bar hider apps have worked at all. Add any other context or screenshots about the feature request here. Not much else to mention. I'm on Ventura, if that helps at all.

**Comment by jakjakob** [comment]
As mentioned in README.md, there is a Command-line version, that doesn't have the menu bar icon.
