### ISSUE TITLE
Launching from Finder or Spotlight fails with: "Error installing battery limiter: undefined" in Ventura, but `open` command succeeds

### ISSUE THREAD

**Issue by nhooey** [actuallymentor/battery#133]
# Workaround

This is the only known way to successfully launch the Battery GUI, in my case:

1. Running `open /Applications/Battery.app` from a terminal

* Update 2023-07-07: This workaround no longer works, Battery fails to launch with all methods.

# Similar bugs:

* #15
* #27
* #55

# Problem

Launching the "Battery" GUI app (`/Applications/Battery.app`) fails when invoked by:

3. Double-clicking `/Applications/Battery.app` from Finder
4. Running `Battery` from Spotlight
5. Adding `/Applications/Battery.app` to `System Settings > Login Items > Open at Login` and rebooting

Where this specific error is emitted:

## Error message:
A dialogue displays this error message:
```
Error installing battery limiter: undefined
```
<img width="328" alt="Error installing battery limiter: undefined" src="https://user-images.githubusercontent.com/65458/230847176-05d7c856-0cba-47f9-bb24-8ac53f126f48.png">

## Details

The error occurs regardless of the permissions of anything in `~/.battery`. No log lines appear in `~/.battery/battery.log` after the error occurs, no menulet appears in Notification Area, and no processes containing a "battery" string are spawned.

If I run `open /Applications/Battery.app` from a terminal, the Battery app starts and shows its menulet in the Notification Area:

## Battery.app Notification Area menulet:

<img width="303" alt="image" src="https://user-images.githubusercontent.com/65458/230847892-d93d5545-c6b1-48a0-9c1f-0b8101c9198a.png">

## System state for error reproduction:

1. Mac OS: Ventura `13.3.1 (22E261)`
1. Battery installed only ever from Homebrew cask (version `1.1.4`), updated today
1. Nothing on the entire system has been installed outside of Homebrew, Nix, and the Mac App Store
1. Permissions opened for config directory: `sudo chmod -Rc a+w ~/.battery`
1. Battery app not already running (Mac OS likely does nothing when invoking an already-running app from Finder or Spotlight)

If I kill the Battery app by clicking "Quit" on its menulet dropdown menu, then all Finder or Spotlight invocations of Battery show the error dialogue shown above in this message, until battery is run with the command: `open /Applications/Battery.app` again.

So there is something wrong specifically with the Spotlight and Finder invocations of Battery.

### After running `open /Applications/Battery.app`:

```
$ ps aux | grep -i battery | egrep -v 'grep|tail'
nhooey           84631   0.0  0.0        0      0   ??  ?     5:05PM   0:00.00 /bin/bash /usr/local/bin/battery discharge 80
nhooey           84619   0.0  0.0        0      0   ??  ?     5:05PM   0:00.00 /bin/bash /usr/local/bin/battery maintain_synchronous 80 --force-discharge
nhooey           84450   0.0  0.0        0      0   ??  ?     5:05PM   0:00.00 /Applications/Battery.app/Contents/Frameworks/battery Helper.app/Contents/MacOS/battery Helper --type=utility --utility-sub-type=network.mojom.NetworkService --lang=en-US --service-sandbox-type=network --user-data-dir=/Users/nhooey/Library/Application Support/battery --shared-files --field-trial-handle=1718379636,r,18185961855328760586,18097394644492592706,131072 --disable-features=SpareRendererForSitePerProcess --seatbelt-client=45
nhooey           84443   0.0  0.0        0      0   ??  ?     5:05PM   0:00.00 /Applications/Battery.app/Contents/Frameworks/battery Helper (GPU).app/Contents/MacOS/battery Helper (GPU) --type=gpu-process --user-data-dir=/Users/nhooey/Library/Application Support/battery --gpu-preferences=UAAAAAAAAAAgAAAIAAAAAAAAAAAAAAAAAABgAAAAAAAwAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAALgFAAAAAAAAuAUAAAAAAADoAQAAPAAAAOABAAAAAAAA6AEAAAAAAADwAQAAAAAAAPgBAAAAAAAAAAIAAAAAAAAIAgAAAAAAABACAAAAAAAAGAIAAAAAAAAgAgAAAAAAACgCAAAAAAAAMAIAAAAAAAA4AgAAAAAAAEACAAAAAAAASAIAAAAAAABQAgAAAAAAAFgCAAAAAAAAYAIAAAAAAABoAgAAAAAAAHACAAAAAAAAeAIAAAAAAACAAgAAAAAAAIgCAAAAAAAAkAIAAAAAAACYAgAAAAAAAKACAAAAAAAAqAIAAAAAAACwAgAAAAAAALgCAAAAAAAAwAIAAAAAAADIAgAAAAAAANACAAAAAAAA2AIAAAAAAADgAgAAAAAAAOgCAAAAAAAA8AIAAAAAAAD4AgAAAAAAAAADAAAAAAAACAMAAAAAAAAQAwAAAAAAABgDAAAAAAAAIAMAAAAAAAAoAwAAAAAAADADAAAAAAAAOAMAAAAAAABAAwAAAAAAAEgDAAAAAAAAUAMAAAAAAABYAwAAAAAAAGADAAAAAAAAaAMAAAAAAABwAwAAAAAAAHgDAAAAAAAAgAMAAAAAAACIAwAAAAAAAJADAAAAAAAAmAMAAAAAAACgAwAAAAAAAKgDAAAAAAAAsAMAAAAAAAC4AwAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAGAAAAEAAAAAAAAAAAAAAABwAAABAAAAAAAAAAAAAAAAgAAAAQAAAAAAAAAAAAAAAJAAAAEAAAAAAAAAAAAAAACwAAABAAAAAAAAAAAAAAAAwAAAAQAAAAAAAAAAAAAAAOAAAAEAAAAAAAAAAAAAAADwAAABAAAAAAAAAAAAAAABAAAAAQAAAAAAAAAAEAAAAAAAAAEAAAAAAAAAABAAAABgAAABAAAAAAAAAAAQAAAAcAAAAQAAAAAAAAAAEAAAAIAAAAEAAAAAAAAAABAAAACQAAABAAAAAAAAAAAQAAAAsAAAAQAAAAAAAAAAEAAAAMAAAAEAAAAAAAAAABAAAADgAAABAAAAAAAAAAAQAAAA8AAAAQAAAAAAAAAAEAAAAQAAAAEAAAAAAAAAAEAAAAAAAAABAAAAAAAAAABAAAAAYAAAAQAAAAAAAAAAQAAAAHAAAAEAAAAAAAAAAEAAAACAAAABAAAAAAAAAABAAAAAkAAAAQAAAAAAAAAAQAAAALAAAAEAAAAAAAAAAEAAAADAAAABAAAAAAAAAABAAAAA4AAAAQAAAAAAAAAAQAAAAPAAAAEAAAAAAAAAAEAAAAEAAAABAAAAAAAAAABwAAAAAAAAAQAAAAAAAAAAcAAAAGAAAAEAAAAAAAAAAHAAAABwAAABAAAAAAAAAABwAAAAgAAAAQAAAAAAAAAAcAAAAJAAAAEAAAAAAAAAAHAAAACwAAABAAAAAAAAAABwAAAAwAAAAQAAAAAAAAAAcAAAAOAAAAEAAAAAAAAAAHAAAADwAAABAAAAAAAAAABwAAABAAAAAQAAAAAAAAAAgAAAAAAAAAEAAAAAAAAAAIAAAABgAAABAAAAAAAAAACAAAAAcAAAAQAAAAAAAAAAgAAAAIAAAAEAAAAAAAAAAIAAAACQAAABAAAAAAAAAACAAAAAsAAAAQAAAAAAAAAAgAAAAMAAAAEAAAAAAAAAAIAAAADgAAABAAAAAAAAAACAAAAA8AAAAQAAAAAAAAAAgAAAAQAAAAEAAAAAAAAAAKAAAAAAAAABAAAAAAAAAACgAAAAYAAAAQAAAAAAAAAAoAAAAHAAAAEAAAAAAAAAAKAAAACAAAABAAAAAAAAAACgAAAAkAAAAQAAAAAAAAAAoAAAALAAAAEAAAAAAAAAAKAAAADAAAABAAAAAAAAAACgAAAA4AAAAQAAAAAAAAAAoAAAAPAAAAEAAAAAAAAAAKAAAAEAAAAAgAAAAAAAAACAAAAAAAAAA= --shared-files --field-trial-handle=1718379636,r,18185961855328760586,18097394644492592706,131072 --disable-features=SpareRendererForSitePerProcess --seatbelt-client=35
nhooey           84387   0.0  0.0        0      0   ??  ?     5:05PM   0:00.00 /Applications/Battery.app/Contents/MacOS/battery
```

### After clicking `Quit` in the Battery menulet in Notification Area:

```
nhooey           84631   0.0  0.0        0      0   ??  ?     5:05PM   0:00.00 /bin/bash /usr/local/bin/battery discharge 80
nhooey           84619   0.0  0.0        0      0   ??  ?     5:05PM   0:00.00 /bin/bash /usr/local/bin/battery maintain_synchronous 80 --force-discharge
```

These last two shell processes are never spawned if `battery` is removed from `System Settings > Login Items > Allow in Background` section, but the `/Applications/Battery.app` GUI application continues to launch and work without issue.

**Comment by rayshan** [comment]
+1 same here with Version 1.1.4

**Comment by SeargantSaxton** [comment]
Mine is not even working from the command line.
same error, undefined

**Comment by matphillips** [comment]
I had the same problem but found that if I run "battery uninstall" from command line, the GUI installer then worked fine. I figure it manages to install the CLI tools, but fails for some reason to install the GUI. Repeated attempts to install fail because it is partially installed already. 
Removing and reinstalling worked fine for me. Your mileage may vary :)

**Comment by nhooey** [comment]
@SeargantSaxton: After upgrading with Homebrew today, my version of Battery is _also_ now failing when launching with this method that worked before:

> 1. Running `open /Applications/Battery.app` from a terminal

**Comment by nhooey** [comment]
> @matphillips: Removing and reinstalling worked fine for me. Your mileage may vary :)

Uninstalling and reinstalling the `battery` cask with Homebrew doesn't fix the problem, running the Battery GUI with all 4 methods mentioned in the issue still fail with the same error message.

**Comment by actuallymentor** [comment]
This is very strange and I have no idea what the source of this could me... If anyone has ideas, please let me know!

**Comment by nhooey** [comment]
Workaround is to just use another equivalent app called “Aldente”. It’s not
all free, but it’s a lot more reliable, and the free version has enough
features.

I looked at the logging code in this app and it’s really lacking some basic
stuff. There’s not much chance that any of these bugs get fixed.

**Comment by SangTruongTan** [comment]
It's also experience on MacOS 14.0 Sonoma. There is no workaround can be a remedy.

**Comment by actuallymentor** [comment]
@SangTruongTan what is the manipulation and power cycle steps you took? Can it help me find the cause?

**Comment by SangTruongTan** [comment]
Hello @actuallymentor,
I've tried to use the GUI, but it was failed. So, I decided to interact with the CLI. During that time, I made some manipulation such as enable/disable charging, maintain battery level. Afterwards, I rebooted my Mac, when it was ready, I tried opening the GUI app and then it worked find (until now).
<img width="350" alt="image" src="https://github.com/actuallymentor/battery/assets/90814057/5c34a681-1b52-4b1b-bb15-257e25bf5e1b">

**Comment by Tweoss** [comment]
I had this issue and determined by running the executable in terminal that I had an error in my `.bashrc`. Removing those lines fixed the error.

**Comment by lucc70** [comment]
@Tweoss 

which lines you removed from the .bashrc file plz ?

**Comment by Tweoss** [comment]
> @Tweoss
> 
> which lines you removed from the .bashrc file plz ?

@lucc70 Les lignes étaient pour une autre application qui n'était pas dans le PATH. Alors, malheureusement, l'erreur a prévenu l'ouverture du script de Battery. Peut-être vous pouvez commenter toutes les lignes dans votre `.bashrc` et ouvrir battery une fois plus?

**Comment by rivolity** [comment]
@lucc70 @Tweoss @SangTruongTan @actuallymentor @nhooey @matphillips @rayshan @SeargantSaxton 

You can fix that by following these steps.
*I had the same probleme yesterday*

- Ensure that the Battery is installed, even if you have the following error message ` Error installing battery limiter: undefined ` just don't uninstall it.
Run this command in terminal
```
which battery
```
You should get this output
```
/usr/local/bin/battery
```
$\color{orange}{Step:2}$
- Run the following command to update the Battery app from the command line.
*this will call the shell script and download the latest script from the git repo and execute the installation via bash.*

```
battery reinstall
```
Press any key to continue and hit enter, this will prompt you to enter the root password, since the shell script need root access to visudo and other privilege.

Here is a screen capture of the running command

<img width="805" alt="image" src="https://github.com/actuallymentor/battery/assets/39197760/8b958084-07bd-4e0f-921b-19f14d52be4b">

Here is the latest version after the update via the CLI.

<img width="352" alt="image" src="https://github.com/actuallymentor/battery/assets/39197760/cfe34251-7f2d-45d8-a786-59219f3ab51f">

**Comment by actuallymentor** [comment]
Thank you @rivolity!

Can someone else confirm this works for them too? It looks like that then the issue is an old version holding things up.

Please reopen is the above does not fix the issue for you.
