### ISSUE TITLE
Error: battery: command not found while installing

### ISSUE THREAD

**Issue by ZibYang** [actuallymentor/battery#141]
**What is the issue? (required)**
Got an error when launch this app at the first time. (installed through brew with `brew install battery`)

**What exactly did you do to produce the issue? (required)**
1. install with `brew install battery`
2. Click on the app icon

**Expected behavior (required)**
The app successfully lanunched

**Screenshots (optional)**
<img width="372" alt="Screenshot 2023-05-08 at 15 14 09" src="https://user-images.githubusercontent.com/40309966/236760415-62fbc70f-a13f-4768-97bc-deb5c62d46ec.png">

**Error logs**
Error installing battery limiter:
Command failed: PATH=/bin:/usri bin:/usr/local/bin:/usr/sbin:/opt/ homebrew battery maintain recover
/bin/bash: battery: command not found

Did `battery` fail to install? Use `tail -n 1000 ~/.battery/*/log` instead.
part of the log:
```
....
Executing PATH=/bin:/usr/bin:/usr/local/bin:/usr/sbin:/opt/homebrew battery maintain recover
Install result success


App initialisation process complete
Update/install error:
Error: Command failed: PATH=/bin:/usr/bin:/usr/local/bin:/usr/sbin:/opt/homebrew battery maintain recover
/bin/bash: battery: command not found
```
**Additional context (optional)**

**Comment by taowaaCool** [comment]
I meet the same problem.

**Comment by dotSpecs** [comment]
I tried again and solved this problem.

**Comment by iSilentP** [comment]
I am also facing same problem. Tried twice to install. Both times from dmg file.

**Comment by ZhiquanW** [comment]
I solved this problem by installing the CLI tool separately.

**Comment by ZibYang** [comment]
I solved this problem by clearing the log file and re-installing it as before, so I will close this issue. Thanks for everyone's help :D
