### ISSUE TITLE
Does using only CLI leave background processes running?

### ISSUE THREAD

**Issue by oscarrutt** [actuallymentor/battery#143]
I'm asking for help, not reporting a bug.

If I use only the CLI and don't keep the GUI app running, is there still a background process running, or does the CLI change a setting in macOS and then quit, leaving the setting until some future action changes it?

**Comment by actuallymentor** [comment]
The CLI keeps running in the background.

**Comment by melyux** [comment]
I can't find any process running in Activity Monitor after doing `battery maintain 80` in Terminal, what's the process called?
