### ISSUE TITLE
`battery maintain` doesn't do discharging.

### ISSUE THREAD

**Issue by parsanoori** [actuallymentor/battery#147]
**What is the issue? (required)**
`battery maintain` doesn't do discharging.

**What exactly did you do to produce the issue? (required)**
1. Install the CLI version
2. When battery is above 80
3. Run `battery maintain 80`
4. Discharge is not enabled. As logs show.

**Expected behavior (required)**
Discharge being enabled.

**Error logs**
```
06/16/23-15:13:26 - Not triggering discharge as it is not requested
06/16/23-15:13:26 - Charging to and maintaining at 80% from 84%
06/16/23-15:13:26 - Charge above 80
06/16/23-15:13:26 - 🔌🪫 Disabling battery charging
```

**Comment by lilianmoraru** [comment]
@parsanoori You have to enable the "Force Discharge" option.
It seems like it was the default behaviour but users complained about it, so now it's an option you need to activate.

**Comment by actuallymentor** [comment]
Thanks for clarifying @lilianmoraru
