### ISSUE TITLE
Starting the battery indicator resets the limit to 80%/ignores user settings

### ISSUE THREAD

**Issue by lilianmoraru** [actuallymentor/battery#149]
**What is the issue? (required)**
I use at home `battery maintain 70` to limit the charging to 70% but I've observed that the "Battery" app resets the charging limit to 80% from time to time without input from the user.
100% reproducible when the indicator is closed(`Quit` option) and then opened again.

**What exactly did you do to produce the issue? (required)**
1. Open `battery` app/indicator
2. From `Terminal`, execute: `battery maintain 70`
3. Check the `battery` indicator for the change to 70%, after which you `Quit` the app
4. Open the `battery` app/indicator again and see that it ignores user settings and sets the limit back to 80%.

**Expected behavior (required)**
The `battery` indicator should not reset the user settings, it should query the current limits and display that value instead, without changing it.
If no value was set, it should set it to 80%(first boot/init).

**Comment by Kriepke** [comment]
indeed, the same

**Comment by actuallymentor** [comment]
Can you confirm this is still an active problem in 1.1.5?

**Comment by wpiekutowski** [comment]
I confirm this is still happening in 1.1.5.

**Comment by armoman92** [comment]
Yeah.  Confirmed on v1.1.5.
-----
Also, the GUI does update its info to the value set in /Users/XXXX/.battery/maintain.percentage. 

 It's just static at "... 80%".  The forced discharge text is also static at "... 80%"

**Comment by mrzhjyw** [comment]
The latest version has the same problem

**Comment by earthsound** [comment]
In the gui.log, I'm seeing an indication that after checking for an update, the following process is run 
```Executing PATH=/bin:/usr/bin:/usr/local/bin:/usr/sbin:/opt/homebrew battery maintain 80``` 
shortly after app initialization.

Just before this, maintain was set to 75.

Snippet:
```Executing ps aux | grep "/usr/local/bin/battery " | wc -l | grep -Eo "\d*"
Found 3 battery related processed to kill
Executing PATH=/bin:/usr/bin:/usr/local/bin:/usr/sbin:/opt/homebrew battery maintain stop
Executing pkill -f "/usr/local/bin/battery.*"
Updating battery...   
Executing PATH=/bin:/usr/bin:/usr/local/bin:/usr/sbin:/opt/homebrew battery update silent
Update result:
No need to update, offline version number v1.0.12 matches remote version number

Executing PATH=/bin:/usr/bin:/usr/local/bin:/usr/sbin:/opt/homebrew battery maintain recover
App initialisation process complete
Executing nohup curl "https://unidentifiedanalytics.web.app/touch/?namespace=battery" > /dev/null 2>&1
Executing PATH=/bin:/usr/bin:/usr/local/bin:/usr/sbin:/opt/homebrew battery status_csv
Force discharge setting: undefined undefined
Executing PATH=/bin:/usr/bin:/usr/local/bin:/usr/sbin:/opt/homebrew battery maintain 80
Battery status:
{"percentage":"18","remaining":"2:24","charging":true,"discharging":false,"battery_state":"18% (2:24 remaining)","daemon_state":"smc charging enabled"}
enable_battery_limiter exec complete
Refreshing tray icon...
Executing PATH=/bin:/usr/bin:/usr/local/bin:/usr/sbin:/opt/homebrew battery status_csv  
Executing PATH=/bin:/usr/bin:/usr/local/bin:/usr/sbin:/opt/homebrew battery status
Battery status:
{"percentage":"18","remaining":"2:24","charging":true,"discharging":false,"maintain_percentage":"80","battery_state":"18% (2:24 remaining)","daemon_state":"smc charging enabled"}
Limiter status message:
07/26/23-18:53:22 - Battery at 18% (2:24 remaining), smc charging enabled
07/26/23-18:53:22 - Your battery is currently being maintained at 80%```

**Comment by earthsound** [comment]
Is this related to #128?

**Comment by lilianmoraru** [comment]
@earthsound Yes, it seems to be the same issue. I think I searched for "reset" and "settings" and did not find a matching issue.
