### ISSUE TITLE
Incorrect URL for liveness check?

### ISSUE THREAD

**Issue by evolutionxbox** [actuallymentor/battery#151]
Mentioned in the [README](https://github.com/actuallymentor/battery/blob/main/README.md)
> `icanhasip.com` is used to see if there is an internet connection

and it's implementation here: https://github.com/actuallymentor/battery/blob/79df4af6b7783fd3392ba573938dd739f8b525fd/app/modules/battery.js#L123

May this be changed? 

The URL is not https, and according to https://radar.cloudflare.com/scan/d203c57e-b08e-4831-b278-68419aaf8bac/dom it doesn't seem to show anything of worth.

May this be changed to use [`https://icanhazip.com`](https://icanhazip.com/) instead? Not only is it [now owned by cloudflare](https://major.io/p/a-new-future-for-icanhazip/), but it actually shows [something useful](https://radar.cloudflare.com/scan/8aa43cec-193b-40f7-9699-bf8f201c59ac/dom).

**Comment by actuallymentor** [comment]
This is indeed the wrong spelling. Please check back in the PR, I appreciate you finding this!
