### ISSUE TITLE
First run fails if behing a proxy 

### ISSUE THREAD

**Issue by lfoppiano** [actuallymentor/battery#168]
First of all, thanks for this app, is very useful!!

**What is the issue? (required)**

I'm behind a proxy and when I started "battery" for the first time, it showed some errors and then the button on the bar was unusable. To close the app was necessary to kill it. 

The issue does not occur when running the app on a normal network. Everything works fine. 
Also **after the first run when the admin credentials are required and the setup is finished, the app works fine** (but I'm not sure the updates are going to work). 

**What exactly did you do to produce the issue? (required)**
1. Open battery
2. An error will appear: "The battery app needs an active internet connection.... blablabla" (sorry I missed to take this screenshot 
3. And then the following: 

   ![image](https://github.com/actuallymentor/battery/assets/15426/3f396c7c-3691-4155-a50f-395675dab05e)
   ![image](https://github.com/actuallymentor/battery/assets/15426/8121320e-c9b4-488c-9f22-dfcac182b1e4)
5. clicking on the battery will not make any effect 

**Expected behavior (required)**
That it works as expected 😅 

**Error logs**
I cannot open them 

```
(base) Lucas-M1-MBP:~ lfoppiano$ tail -n 1000 ~/.battery/*/log
tail: /Users/lfoppiano/.battery/*/log: No such file or directory
```

**Comment by earthsound** [comment]
> **Error logs** I cannot open them

Runing `battery logs` may provide useful logs to share

**Comment by actuallymentor** [comment]
Hey!

First fun clones the Github repo in the background, not sure how your network is set up but I presume that it blocks the app from talking to Github somehow.

Updates will not work, these require internet too :)
