### ISSUE TITLE
Icon not updating

### ISSUE THREAD

**Issue by emilianogtlp** [actuallymentor/battery#17]
I ran the command `battery charge off` and got as a response:

`23:22:59 - Enabling battery charging`
`23:22:59 - Battery at 100% (0:00 remaining), smc charging enabled`
`23:22:59 - Charging to 80% from 100%`
`23:22:59 - Enabling battery charging`
`23:22:59 - Disabling battery charging`
`23:22:59 - Charging completed at 100%`

But the icon of powering is still shown on the menu bar, is it working?

**Comment by actuallymentor** [comment]
The command is `battery charging off` or `battery charge NUMBER` like `battery charge 70`.
