### ISSUE TITLE
Battery is charged to 100% when powered off

### ISSUE THREAD

**Issue by M4R774** [actuallymentor/battery#175]
**What is the issue? (required)**
My battery was holding at 60%. I shut down my Mac. Next day my battery is at 100%. 

**What exactly did you do to produce the issue? (required)**
I was using Mac with M2 CPU and it was connected to Belkin Dock with USB-C. 

**Expected behavior (required)**
I excpected, that my battery level would be 50 - 60 % after the night powered off. 

**Error logs**
❯ battery logs
👾 Battery CLI logs:

09/06/23-13:46:42 - Not triggering discharge as it is not requested
09/06/23-13:46:42 - Charging to and maintaining at 80% from 100%
09/06/23-13:46:42 - Charge above 80
09/06/23-13:46:42 - 🔌🪫 Disabling battery charging
09/06/23-13:46:42 - 💡 Setting magsafe color to green
09/06/23-13:49:32 - Not triggering discharge as it is not requested
09/06/23-13:49:32 - Charging to and maintaining at 50% from 100%
09/06/23-15:16:19 - Not triggering discharge as it is not requested
09/06/23-15:16:19 - Charging to and maintaining at 75% from 78%
09/06/23-15:26:20 - Charge below 75
09/06/23-15:26:20 - 🔌🔋 Enabling battery charging
09/06/23-15:26:20 - 🔼🪫 Disabling battery discharging
09/06/23-15:26:20 - 💡 Setting magsafe color to orange
09/06/23-15:30:20 - Charge above 75
09/06/23-15:30:20 - 🔌🪫 Disabling battery charging
09/06/23-15:30:21 - 💡 Setting magsafe color to green
09/06/23-15:31:44 - Not triggering discharge as it is not requested
09/06/23-15:31:44 - Charging to and maintaining at 60% from 75%
09/06/23-16:53:48 - Charge below 60
09/06/23-16:53:48 - 🔌🔋 Enabling battery charging
09/06/23-16:53:48 - 🔼🪫 Disabling battery discharging
09/06/23-16:53:48 - 💡 Setting magsafe color to orange
09/06/23-16:56:48 - Charge above 60
09/06/23-16:56:48 - 🔌🪫 Disabling battery charging
09/06/23-16:56:48 - 💡 Setting magsafe color to green
09/07/23-08:19:38 - Debug trail. User: aleksi.martikainen, config folder: /Users/aleksi.martikainen/.battery, logfile: /Users/aleksi.martikainen/.battery/battery.log, file called with 1: maintain_synchronous, 2: recover
09/07/23-08:19:38 - Recovering maintenance percentage 60
09/07/23-08:19:38 - Not triggering discharge as it is not requested
09/07/23-08:19:38 - Charging to and maintaining at 60% from 100%
09/07/23-08:19:38 - Charge above 60
09/07/23-08:19:38 - 🔌🪫 Disabling battery charging
09/07/23-08:19:38 - 💡 Setting magsafe color to green

🖥️  Battery GUI logs:

tail: /Users/aleksi.martikainen/.battery/gui.log: No such file or directory

📁 Config folder details:

total 24
drwxr-xr-x@  5 aleksi.martikainen  staff   160B  6 Syy 13:46 .
drwxr-x---+ 42 aleksi.martikainen  staff   1,3K  7 Syy 08:33 ..
-rwxr-xr-x@  1 aleksi.martikainen  staff   1,9K  7 Syy 08:33 battery.log
-rwxr-xr-x@  1 aleksi.martikainen  staff     6B  6 Syy 15:31 battery.pid
-rw-r--r--@  1 aleksi.martikainen  staff     3B  6 Syy 15:31 maintain.percentage

⚙️  Battery data:

09/07/23-08:33:55 - Battery at 100% (0:00 remaining), smc charging disabled
09/07/23-08:33:55 - Your battery is currently being maintained at 60%
Battery CLI utility v1.1.5

**Comment by jakjakob** [comment]
That is a software limitation, as now you have to leave your MacBook open while charging
