### ISSUE TITLE
Battery is limited at 92% and not 80%

### ISSUE THREAD

**Issue by maxrmp** [actuallymentor/battery#177]
The charge is stopping at 92% and not at 80%

I just recently installed it, did tow charges during night, one without force-discharging and one with. nothing change between the two charges 
<img width="532" alt="Capture d’écran 2023-09-09 à 12 52 38" src="https://github.com/actuallymentor/battery/assets/123120982/bde30865-2d39-4c98-ae23-598db0a10f5f">

**Comment by jakjakob** [comment]
are you sure if the maintain level is correct? You can check via GUI seeing if the checkmark is on "enable 80% battery limit". If it is, can you send some logs with `battery logs`?
