### ISSUE TITLE
M2 Air charges more than 80%

### ISSUE THREAD

**Issue by hardcod3dd** [actuallymentor/battery#178]
**What is the issue? (required)**

M2 Air charges more than 80%

**What exactly did you do to produce the issue? (required)**
My laptop was open.software was running as usual.battery at 80%,then I shutdown the computer.remove the magsafe and after 1-2 hours open up the laptop again and the battery is at 83%.

**Expected behavior (required)**
battery should be 80 or less

**Screenshots (optional)**

**Error logs**

**Comment by jakjakob** [comment]
probably  https://github.com/actuallymentor/battery/pull/163 will fix the problem (for 80% charge limit)

**Comment by hardcod3dd** [comment]
its interesting to see apple implemented a firmware based limit.would be very useful for it to work even when the laptop is powered off.thanks for the tip.closing the issue for now.
