### ISSUE TITLE
FR: Set scheduled departure time

### ISSUE THREAD

**Issue by gajavegr** [actuallymentor/battery#181]
**Is your feature request related to a problem? Please describe.**

This feature is **not** related to a problem with `battery`, it is merely a QoL improvement for users who typically leave their computer at < 80% while plugged into the adapter for the purpose of extending battery life.

**Describe the solution you'd like**
For a user who typically leaves their MacBook at <80%, on days when they know they will need the battery charged to 100% for maximum battery life, but still want to minimize the amount of time the battery is at a high SoC, allow the user to set a desired time by which the battery is charged to 100%. This will prevent users from charging their MacBook to 100% earlier than needed or waking up in the middle of the night to start charging it at the last possible moment themselves.

Using the CLI, I propose a new command: `scheduled-departure`
`battery scheduled-departure LEVEL[1-100] TIME_OF_DAY[0000 - 2359]`
`     charge the battery to a certain percentage, and disable charging when that percentage is reached`
`     delay the start of charging so that the battery reaches the desired percentage by the desired time of day`
`     eg: battery scheduled-departure 100 0800`

**Describe alternatives you've considered**
The only alternatives are to either 1) let your computer start charging to the desired percentage early 2) setting alarms to wake up during the night to set the charge limit to desired so that it's ready by the morning

**Additional context**
Proposing no change to the Menu Bar icon/menu, but add new info to CLI `Usage` section.

**Comment by actuallymentor** [comment]
Interesting idea. It's beyond the scope of what I intended `battery` for, but if you have the time to draft a PR I'd be happy to merge it!
