### ISSUE TITLE
Maintain battery between 65-75%

### ISSUE THREAD

**Issue by anarchy89** [actuallymentor/battery#187]
I currently just charge to 75% and run battery charging off.

Then I leave it for a few weeks like that and when it drops to 65% i let it go back to 75% before disabling it again.

Is it possible so create a function that lets it charge to 75 and stops, then when it drops to 65, it charges it back to 75?

**Comment by fuzetsu** [comment]
It should be relatively simple to create a bash script, and run it on a schedule through a cron job to handle this.

<details>
<summary>
I asked ChatGPT and got a fairly plausible solution back (although I didn't test it).
</summary>

You: what's the easiest way to setup a cron job on mac os
––––––––––––––––––––––––––––––––––––––––
GPT: The easiest way to set up a cron job on macOS is through the built-in launchd service, which is more modern and flexible than the traditional cron system. Here's how you can do it:

1. Open Terminal (Applications -> Utilities -> Terminal).

2. Use the `crontab` command to edit your user's cron configuration:

   ```
   crontab -e
   ```

3. This will open the cron file in the default text editor. Add your cron job entry following the cron syntax. For example, to run a script every day at 8:00 AM, you can add:

   ```
   0 8 * * * /path/to/script.sh
   ```

   Save and exit the editor.

4. The cron job is now created, but to activate it through launchd, you need to unload and load the cron jobs. Run the following commands:

   ```
   launchctl unload ~/Library/LaunchAgents/com.apple.user.launchd.plist
   launchctl load ~/Library/LaunchAgents/com.apple.user.launchd.plist
   ```

   Note: This will unload and load all user-specific launchd jobs, including cron jobs.

5. Your cron job is now scheduled and active on your macOS system.

To view your cron jobs, you can run `crontab -l` command.

Remember to include the full path to your script or executable file in the cron job entry to ensure it runs correctly. Also, make sure your script is executable (`chmod +x /path/to/script.sh`) if it is not already.

Note: If you prefer to stick with the traditional cron system on macOS, you can use `sudo crontab -e` to access the system-wide cron configuration, though this is not recommended unless you have specific requirements.
––––––––––––––––––––––––––––––––––––––––
You: help me write a script for this cronjob that runs `battery maintain 75` when the battery falls to 65% and `battery maintain 65` when the battery reaches 75%
 ––––––––––––––––––––––––––––––––––––––––
GPT: Certainly! Here's a script that you can use for your cron job:

```bash
#!/bin/bash

# Desired battery thresholds
LOW_THRESHOLD=65
HIGH_THRESHOLD=75

# Get current battery level as a percentage
battery_level=$(pmset -g batt | grep -o '[0-9]*%' | tr -d '%')

# Check if battery level is below the low threshold
if [ $battery_level -le $LOW_THRESHOLD ]; then
  # Run command to maintain battery at 75%
  battery maintain $HIGH_THRESHOLD
elif [ $battery_level -ge $HIGH_THRESHOLD ]; then
  # Run command to maintain battery at 65%
  battery maintain $LOW_THRESHOLD
fi
```

Save the script to a file, e.g., `battery_maintenance.sh`. Make sure to give it execute permissions by running `chmod +x battery_maintenance.sh`.

Next, you can add the script as a cron job by editing your user's cron configuration:

```bash
crontab -e
```

Add the following line to the crontab to schedule the script to run every minute:

```bash
* * * * * /path/to/battery_maintenance.sh
```

Save and exit the editor.

This cron job will run the script every minute, checking the battery level and executing the appropriate command when the thresholds are crossed.
––––––––––––––––––––––––––––––––––––––––
You: the current maintain percentage is stored in "$HOME/.battery/maintain.percentage", so read that and only call maintain in the script if it's different than the current setting
––––––––––––––––––––––––––––––––––––––––
GPT: Sure! Here's an updated version of the script that reads the current maintain percentage from the `"$HOME/.battery/maintain.percentage"` file and only calls `battery maintain` if it's different than the current setting:

```bash
#!/bin/bash

# Desired battery thresholds
LOW_THRESHOLD=65
HIGH_THRESHOLD=75

# Path to the maintain percentage file
MAINTAIN_FILE="$HOME/.battery/maintain.percentage"

# Get current battery level as a percentage
battery_level=$(pmset -g batt | grep -o '[0-9]*%' | tr -d '%')

# Read current maintain percentage from file
current_maintain_percentage=$(cat "$MAINTAIN_FILE")

# Check if battery level is below the low threshold
if [ $battery_level -le $LOW_THRESHOLD ] && [ $current_maintain_percentage -ne $HIGH_THRESHOLD ]; then
  # Run command to maintain battery at 75%
  battery maintain $HIGH_THRESHOLD
elif [ $battery_level -ge $HIGH_THRESHOLD ] && [ $current_maintain_percentage -ne $LOW_THRESHOLD ]; then
  # Run command to maintain battery at 65%
  battery maintain $LOW_THRESHOLD
fi
```

Make sure to update the `MAINTAIN_FILE` variable to the correct path where the maintain percentage is stored.

Save the script and give it execute permissions using `chmod +x battery_maintenance.sh`.

Add the script as a cron job in your user's cron configuration as explained earlier. Now the script will only call `battery maintain` when the current maintain percentage stored in the file is different than the desired threshold.
</details>

**Comment by fuzetsu** [comment]
I ended up trying out the script it generated, and eventually I just rewrote it myself in ruby. 

I have been using it for a couple weeks now and it has been working well 👍 

```ruby
#!/usr/bin/env ruby

LOW = 70
HIGH = 80

CURRENT_SETTING = File.read("#{ENV['HOME']}/.battery/maintain.percentage").to_i
CURRENT_BATTERY = /([0-9]+)%/.match(`pmset -g batt`)[1].to_i

def notify(msg)
  `osascript -e 'display notification "#{msg}" with title "Battery Watcher"'`
end

def maintain(percent)
  return if percent == CURRENT_SETTING 
  notify("Maintaining battery at #{percent}%")
  `/usr/local/bin/battery maintain #{percent}`
end

if CURRENT_BATTERY <= LOW
  maintain(HIGH)
elsif CURRENT_BATTERY >= HIGH
  maintain(LOW)
end
```

I have it configured to run every 15 minutes, could be even less often though.

```cron
*/15 * * * * $HOME/code/cron/battery-watcher
```

**Comment by actuallymentor** [comment]
You are not the only one that seems to care about this. Do you have time to draft a PR?

Let's continue the convo in #222
