### ISSUE TITLE
MBP charging enable after reboot eventhough high battery level

### ISSUE THREAD

**Issue by adowls** [actuallymentor/battery#19]
It worked well after installed. But while reboot and run "battery status"

>  _10:16:40 - Battery at 98% (0:23 remaining), smc charging enabled
>  10:16:40 - Your battery is currently being maintained at 80%_

MBP start charging after reboot eventhough 98% battery level.
Thanks.

**Comment by emsquid** [comment]
same problem here, I'm using the cli and the battery maintaining isn't reboot persistent...

**Comment by actuallymentor** [comment]
@adowls PR should have fixed this, thank you!
