### ISSUE TITLE
Unintentional charging while in sleepmode

### ISSUE THREAD

**Issue by TomTebetobsi** [actuallymentor/battery#190]
**What is the issue? (required)**
Battery randomly charges when in sleep mode, gaining 5-10% 

**What exactly did you do to produce the issue? (required)**
Usually after plugging it in, it charges to 80% as it should be. The following day I see the battery at more percent then I left it. 

**Expected behavior (required)**
Stay at 80%

**Screenshots (optional)**
![Bildschirmfoto 2023-10-13 um 09 27 29](https://github.com/actuallymentor/battery/assets/147803750/45af0073-cedb-44e9-bdbd-aa11d33bf776)
Over night 

![Bildschirmfoto 2023-11-24 um 21 27 13](https://github.com/actuallymentor/battery/assets/147803750/ed65993e-3115-4da1-abff-e9ad8056ca09)
Closed lid after Work (with display times) 

**Error logs**
10/12/23-08:59:23 - Charge above 80
10/12/23-08:59:23 - 🔌🪫 Disabling battery charging
10/12/23-08:59:23 - 💡 Setting magsafe color to green
10/13/23-09:17:38 - Triggering discharge to 80 before enabling charging limiter
10/13/23-09:17:38 - Discharging to 80% from 90%
10/13/23-09:17:38 - 🔽🪫 Enabling battery discharging
10/13/23-09:17:38 - Battery at 90% (target 80%)
(I used force discharging to get back to 80%)

10/13/23-09:32:25 - Battery at 90% (8:43 remaining), smc charging enabled
10/13/23-09:32:25 - Your battery is currently being maintained at 80%

**Additional context (optional)**
Happens every one in a wile. Sometimes 2%, sometimes 6%...
Thank you for this amazing tool :)

**Comment by Noire86** [comment]
Same behaviour for me. It jumps up to 92% while charging in sleep mode

**Comment by posen4u** [comment]
Same here, 14-inch 2021 M1 Pro, Sonoma 14.1.1. 

Got 93% on the first test. Plugged in at ish-25%, closed the lid. A few moments later when opening the lid: 93%.
14-inch 2021 M1 Pro, Sonoma 14.1.1

11/22/23-20:47:16 - Battery at 93% (14:11 remaining), smc charging disabled
11/22/23-20:47:16 - Your battery is currently being maintained at 80%

<img width="624" alt="image" src="https://github.com/actuallymentor/battery/assets/88683786/0c7d078b-4750-4ac4-a33e-348de7f55b27">

**Comment by actuallymentor** [comment]
This is an odd (but known) issue. It's on the the investigate list. Thanks for reporting it!
