### ISSUE TITLE
Add Calibration Mode for elimination battery miscalibration

### ISSUE THREAD

**Issue by djbob2000** [actuallymentor/battery#191]
If you keep your battery at lower percentages for a longer time with no or little charging/discharging, notebooks turning off at 50% or even higher percentages.

**Describe the solution you'd like**
Schedule every other week charge up to 100%, and stay there for an hour before it starts discharging again to your desired charging percentage.

More details
https://apphousekitchen.com/feature-explanation-calibration-mode-2/

**Comment by actuallymentor** [comment]
Should be included soon due to #169
