### ISSUE TITLE
Add sailing mode like Al dente. Also the magsafe support, when battery is at set battery level, it will turn green and stop charging. 

### ISSUE THREAD

**Issue by Confidack** [actuallymentor/battery#194]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by panzer-arc** [comment]
My MagSafe light is green and charging is limited to 80%. I think that may already be included.

**Comment by sanketshahanebookendai** [comment]
I think what @Confidack is asking for is to let the battery fluctuate between say 70% and 80% in order to avoid trickle charging.

**Comment by FUFAFUFA** [comment]
+1

**Comment by actuallymentor** [comment]
Issue template is not decorative.
