### ISSUE TITLE
is this work when lid is close ?

### ISSUE THREAD

**Issue by tchek** [actuallymentor/battery#196]
**What is the issue? (required)**
Is this app work with the lid close ?

**Expected behavior (required)**
when the lid is close battery do not work ?

**Comment by hexclann** [comment]
@tchek If the Mac goes to sleep this app does not work. That can be fixed if the PR https://github.com/actuallymentor/battery/pull/163 gets merged.

**Comment by kushal10** [comment]
@tchek works for me? even when the lid is closed! I use the cli version

**Comment by tchek** [comment]
> [@kushal10 ](https://github.com/kushal10) ??

**Comment by actuallymentor** [comment]
It should work (and does for me), but some users report issues. It's on the list of "to investigate".
