### ISSUE TITLE
scheduled full charging

### ISSUE THREAD

**Issue by Alessandro15204** [actuallymentor/battery#198]
**Is your feature request related to a problem? Please describe.**
Subject: Feature Request - Customizable Full Charging Schedule

Dear ActuallyMentor

I hope this message finds you well. I am writing to express my appreciation for the efforts put into the development of the Optimized Battery Charging feature for Mac. However, I have encountered a challenge due to the variable nature of my schedule, which, I believe, is a common issue for many users.

The Apple’s built in Optimized Battery Charging relies on the Mac learning from daily charging habits to restrict charging beyond 80%. Unfortunately, my schedule is highly unpredictable due to varying class timings. Consequently, my Mac has not been able to adapt to my routine effectively.

I find the Actuallymentor Battery project extremely helpful, I would like to propose a feature that I believe could enhance its usability significantly. 
My suggestion is to introduce an option that allows users to customize the full charging schedule. Similar to Apple's existing feature, I envision the ability to set a specific time schedule during which the Mac can charge from 80% to 100%.

For instance, it would be immensely helpful if I could configure my Mac to commence charging from 80% to 100% at 5:30 am, ensuring that the charging process is complete by the time I wake up at 6 am. I understand that this application is not intended to replace Apple's built-in features entirely, but incorporating such customization would be a valuable addition for users with dynamic schedules.

I believe that this feature would not only cater to my specific needs but would also benefit a broader user base facing similar challenges. Thank you for considering my suggestion, and I appreciate the dedication to continuously improving this already valuable tool.

( I used AI toto fix my typos since i’m not native english, if this text seems a little weird that’s why)

Best Regards,

**Describe the solution you'd like**
The proposed feature aims tointroduce a customizable charging schedule. This feature would allow  users to set specific time frames  which their Macs can start charging from 80% to 100%, allowing for a more personalized and adaptive charging experience.
Key Components:

allow a simple schedule like as said above  for example  that starts charging at 5:30 when i have to get up at 6:00

 this customizable full charging schedule feature may offer users a more tailored and adaptive solution to address the challenges posed by variable schedules, enhancing the overall utility of the tool.

**Describe alternatives you've considered**

**Additional context**
![Untitled129_20231120091730](https://github.com/actuallymentor/battery/assets/98517560/4a2698b3-698b-4074-87ac-96aea1838d55)
(forgive my poor design skills)

**Comment by actuallymentor** [comment]
Thank you for your issue @Alessandro15204! And don't worry about your English or design skills, my Basque (guess based on your screenshot?) is not very good either :)

This feature is unlikely to be added to the GUI since we're trying to keep that as minimalistic as possible.

However, the behaviour you mention is relatively easy to achieve using a cronjob, you could:

1. Open your crontab with `crontab -e`
2. Use https://crontab.guru/ to generate cron schedules
3. Call `battery maintain 80` and `battery maintain 100` at those different times

Please feel free to re-open this issue if you have further questions!
