### ISSUE TITLE
Cli command help

### ISSUE THREAD

**Issue by anarchy89** [actuallymentor/battery#199]
Hi, I would like to know what the difference is between battery charging off and battery adapter off. They both disable charging yes, not sure what the difference is.

Also, if I do battery discharge 50, how do I turn it off after that? Do I just leave it and do battery charging off? 

Thanks!

**Comment by actuallymentor** [comment]
The one disables charging (but draws power from the adapter, so the battery is unused), and the other disables the adapter (and draws power from the battery, to drain it)
