### ISSUE TITLE
Set level for battery limit

### ISSUE THREAD

**Issue by kimhnotes** [actuallymentor/battery#200]
Please add a feature like AlDente where user can specify battery level at which to stop charging.

**Comment by hexclann** [comment]
`battery maintain 80` command will turn off the charging when it reaches 80% or  `battery charging off` to stop the charging regardless the battery percentage you're having

**Comment by ballo** [comment]
He might be referring to the GUI app which, for whatever reason, forces you to use 80%

**Comment by actuallymentor** [comment]
The GUI is set to 80, this can be changed through the CLI as @hexclann mentioned.

@ballo the reason is minimalism in the design and code complexity. GUI does 80 only, CLI does anything you want and much more.
