### ISSUE TITLE
Don't work on MacBook Pro 16 M2 Max on 13.6.2

### ISSUE THREAD

**Issue by ALEUT** [actuallymentor/battery#202]
**What is the issue? (required)**
Doesn't work on MacBook Pro 16 M2 Max on 13.6.2

**What exactly did you do to produce the issue? (required)**
Installed using brew, set limit at 80%. Set discharge to 80%. Notebook doesn't react on that, I discharged it manually, and after connecting the charger it charged to 100% again.

**Expected behavior (required)**
Keep charge at 80%

**Comment by PiotrRaszkowski** [comment]
I have the same model, works fine, keeps 80%.

**Comment by ALEUT** [comment]
I installed it using brew and it looks smc is not installed:
`command not found: smc`
Probably it's the reason why it doesn't work.

**Comment by ALEUT** [comment]
Reinstalled again and it really works!
