### ISSUE TITLE
Battery limiter error: Cannot read properties of undefined (reading 'includes')

### ISSUE THREAD

**Issue by rosch100** [actuallymentor/battery#203]
**What is the issue? (required)**
An error message displaying 
'Battery limiter error: Cannot read properties of undefined (reading
'includes')'
popped up. The battery icon was grey, but after clicking on it, all info was displayed correctly.

I could not find any log entries in the system console. The battery log did not record any problems.
[battery.log](https://github.com/actuallymentor/battery/files/13463520/battery.log)
<img width="298" alt="Bildschirmfoto 2023-11-25 um 10 23 17" src="https://github.com/actuallymentor/battery/assets/5745224/f4b5c41d-856d-459d-999c-51b34dbccd39">

**Comment by benzht** [comment]
Same here. And the logs show
🚨 Missing image: /Applications/battery.app/Contents/Resources/battery-active-NaN-Template.png

**Comment by dynek** [comment]
I'm having the same popup here on a M1 Pro.

When this occurs, is it also freezing your GUI ?

**Comment by maxemillianian** [comment]
M2 MacBook Air: When resuming from sleep, I'm getting the popup. No system freezes, though.

**Comment by actuallymentor** [comment]
Could you try the latest release and re-open this issue if the problem persists?
