### ISSUE TITLE
Still charging above 80 % and MagSafe light orange when at or above 80%

### ISSUE THREAD

**Issue by samuelaweeks** [actuallymentor/battery#205]
Erratically charges above 80% when Battery is set to "Enable 80% battery limit, particularly while in sleep mode and not using significant battery power while active. Charged to 100% yesterday while the MagSafe light was green, so I enabled force discharge to bring it back to 80%. Now the MagSafe light is staying orange but it finally seems to be maintaining the 80% limit.

Expected behaviour:
Charges to 80%, MagSafe light turns green and stays at 80% while in use or in sleep mode.

M2 MacBook Pro 2023, macOS Sonoma 14.1.1 (23B81).

**Comment by hexclann** [comment]
Can be fixed if PR https://github.com/actuallymentor/battery/pull/163 gets merged
