### ISSUE TITLE
Feature request: Support for Desktop Widget

### ISSUE THREAD

**Issue by chrisfromredfin** [actuallymentor/battery#206]
**Is your feature request related to a problem? Please describe.**
I'm curious, at-a-glance, to know what my current settings are for battery. I would typically open the CLI and do `battery status`

**Describe the solution you'd like**
With desktop widgets in macOS Sonoma, it would be nice to simply drop that information into a tiny status widget on my desktop.

**Describe alternatives you've considered**
I looked for some sort of third-party app that has a way to turn any CLI commands into widgets, but haven't had much luck with anything that uses native widgets (they are very new).

**Additional context**
ex.g. for a different app AutoSleep, and options for adding widgets.
<img width="831" alt="widgets" src="https://github.com/actuallymentor/battery/assets/278442/fef78e0c-14f1-4226-bdac-443f52abbbbe">

**Comment by actuallymentor** [comment]
I like your thinking, but I'm afraid this is outside of the scope of this project.

That said, if you know how to make widgets (which I do not), you can very easily adapt the battery CLI as a data source!
