### ISSUE TITLE
Battery level can be set to more than 100%

### ISSUE THREAD

**Issue by ksgubanov** [actuallymentor/battery#210]
**What is the issue? (required)**
the 'battery charge' CLI command accepts numbers more than 100%

**What exactly did you do to produce the issue? (required)**
1. Execute command 'battery charge 250'
2. Observe the successful command execution(infinite waiting to reach the provided value)

**Expected behavior (required)**
The command should, according to its description in the help output, whether inform the user about the invalid parameter and stop execution or to limit the value to the maximal allowed (100)

**Screenshots (optional)**
Would not differ from the "Error logs" section

**Error logs**
> \> battery charge 250
12/07/23-15:36:02 - Killing running maintain daemons & enabling charging as default state
12/07/23-15:36:02 - Disabling daemon at gui/501/com.battery.app
12/07/23-15:36:02 - 🔌🔋 Enabling battery charging
12/07/23-15:36:02 - 🔼🪫 Disabling battery discharging
12/07/23-15:36:02 - 💡 Setting magsafe color to
12/07/23-15:36:02 - Battery at 100% (charge; remaining), smc charging enabled
12/07/23-15:36:02 - Setting adapter to on
12/07/23-15:36:02 - Killing running maintain daemons & enabling charging as default state
12/07/23-15:36:02 - Disabling daemon at gui/501/com.battery.app
12/07/23-15:36:02 - 🔌🔋 Enabling battery charging
12/07/23-15:36:02 - 🔼🪫 Disabling battery discharging
12/07/23-15:36:02 - 💡 Setting magsafe color to
12/07/23-15:36:02 - Battery at 100% (charge; remaining), smc charging enabled
12/07/23-15:36:02 - 🔽🪫 Enabling battery discharging
12/07/23-15:36:02 - Charging to 250% from 100%
12/07/23-15:36:02 - 🔌🔋 Enabling battery charging
12/07/23-15:36:02 - 🔼🪫 Disabling battery discharging
12/07/23-15:36:02 - Battery at 100%
12/07/23-15:37:02 - Battery at 100%
12/07/23-15:38:02 - Battery at 100%

**Comment by actuallymentor** [comment]
Ah that is an interesting validation catch indeed! Thanks for taking the time for reporting it.

Do you have the bandwidth to draft a PR?
