### ISSUE TITLE
Possibility to pause charge when battery has reached desired %.

### ISSUE THREAD

**Issue by FUFAFUFA** [actuallymentor/battery#213]
A charging mode that allows the charging to stop when it reach for example 80% (upper limit) and then when the battery reach for example 70% (lower limit), the charging will start again.

**Describe the solution you'd like**
Settings that allow me to set limits like illustrated over here.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by Cipher-08** [comment]
We can use a combination of battery APIs and a control mechanism to start and stop charging based on these limits.

**Comment by actuallymentor** [comment]
Cool idea, do you have the time to draft a pull request for this?

Closing as duplicate of #222, let's continue our chat there.
