### ISSUE TITLE
Time Machine backups not starting reliably when "Back up on battery power" is off

### ISSUE THREAD

**Issue by blackketter** [actuallymentor/battery#234]
Not sure if this is an actual bug, documentation suggestion, or what, but I've found that my automatic Time Machine backups have not been kicking in reliably.  I wonder if it's because the TM setting "Back up on battery power" has been turned off.  

It appears that if Time Machine tries to start a backup and Battery has paused charging, then the backup doesn't begin (and an attempt is recorded in the Time Machine preferences plist).  

Turning on "Back up on battery power" seems to make it more reliable.

**Comment by winstonford** [comment]
I am backing up every day on auto with Backup on battery power OFF, and so far no problems.  I back up to a 1TB sd card that remains in the slot.

**Comment by blackketter** [comment]
My Time Machine issues don't appear to be related to Battery.  Sorry for the false alarm.
