### ISSUE TITLE
CLI command to show active/current settings

### ISSUE THREAD

**Issue by jonasbjorklundsvensson** [actuallymentor/battery#260]
Hi,

New user here, so maybe I missed something, but:

It would be nice if there was also a CL command to show what settings are currently applied, for max/min charge for charging, etc. For forgetful people such as myself :)

**Comment by aschiletus** [comment]
battery status ?

**Comment by jonasbjorklundsvensson** [comment]
Ah, it wasn't at all clear to me from the command description that such info was also provided, thanks!
