### ISSUE TITLE
MacOS 13 M1 Not in effect

### ISSUE THREAD

**Issue by almightyYantao** [actuallymentor/battery#30]
![image](https://user-images.githubusercontent.com/34707560/204806212-87357957-de69-4ff3-87f6-4ead1cdb725d.png)

**Comment by almightyYantao** [comment]
![image](https://user-images.githubusercontent.com/34707560/204806291-ff96ff9d-b5aa-4ecd-920b-f4dafec422bc.png)

**Comment by love4taylor** [comment]
```
~
❯ battery status
18:03:08 - Battery at 80% (attached; remaining), smc charging disabled
18:03:08 - Your battery is currently being maintained at 80%
```
<img width="303" alt="SCR-20221202-p36" src="https://user-images.githubusercontent.com/6081912/205267983-7253c90a-5240-4daa-82e5-e522d55a8c9d.png">

<img width="612" alt="SCR-20221202-p3z" src="https://user-images.githubusercontent.com/6081912/205268007-29a66ae6-a0f6-4e49-b839-08f85bfdb89f.png">

**Comment by almightyYantao** [comment]
![image](https://user-images.githubusercontent.com/34707560/205802261-0569a314-2079-451d-9fca-8022258e7ec1.png)
![image](https://user-images.githubusercontent.com/34707560/205802294-661f15e4-129c-482e-9809-84554d3fc204.png)
![image](https://user-images.githubusercontent.com/34707560/205802344-caaac9f9-f264-4de9-9758-35e929578dd9.png)

**Comment by safferli** [comment]
you will need to disable the MacOS-specific automatic battery monitoring, I believe

**Comment by actuallymentor** [comment]
I do not speak Chinese I'm afraid, did you solve the issue?
