### ISSUE TITLE
Not working at macOS 12.3.1(M1 Pro MacBookPro 14")

### ISSUE THREAD

**Issue by Steve-Xyh** [actuallymentor/battery#4]
Thanks for your scripts!
But after I run `battery charging off` the battery icon does not  have any changes...😢

**Comment by Steve-Xyh** [comment]
I checked the `CH0B` and `CH0C` values, they are set to `00` after running `battery charging on`, which makes sense.
But they are set to `03` after running `battery charging off`, it should be `02`. I don't know about SMC hardware things, so I'm not sure what happened. I would be very grateful if you could help me.

This is the script output
<img width="878" alt="image" src="https://user-images.githubusercontent.com/33098678/166254071-8e1b1e00-3458-4785-98de-882f658ffeff.png">

**Comment by anarchy89** [comment]
I had this problem on my MacBook 16 m1 max, I typed battery charging off, then I removed the power cable and plugged it back in and now it works as intended.

**Comment by kitrak4002** [comment]
Hello, I'm a new Macbook M1 user and not into as much coding and I don't have much experience using the terminal. I used the one-line installation for the Battery cli tool. However, I don't know how to use the commands in the terminal for the Battery cli tool. It would be helpful if anyone posted specifically what to type to get the commands going. Thank you!

**Comment by tob-00** [comment]
> Hello, I'm a new Macbook M1 user and not into as much coding and I don't have much experience using the terminal. I used the one-line installation for the Battery cli tool. However, I don't know how to use the commands in the terminal for the Battery cli tool. It would be helpful if anyone posted specifically what to type to get the commands going. Thank you!

Hi! it worked for me running it as administrator (MacBook Air M2): 
`sudo curl https://raw.githubusercontent.com/actuallymentor/battery/main/setup.sh | sudo bash`

Hope that helps :)

**Comment by kitrak4002** [comment]
Thank you so much! It is working now!

**Comment by anarchy89** [comment]
> > Hello, I'm a new Macbook M1 user and not into as much coding and I don't have much experience using the terminal. I used the one-line installation for the Battery cli tool. However, I don't know how to use the commands in the terminal for the Battery cli tool. It would be helpful if anyone posted specifically what to type to get the commands going. Thank you!
> 
> Hi! it worked for me running it as administrator (MacBook Air M2): `sudo curl https://raw.githubusercontent.com/actuallymentor/battery/main/setup.sh | sudo bash`
> 
> Hope that helps :)

Hi @tob-00 do you have to unplug and plug back in the charger whenever you do battery charging off in the terminal?

**Comment by tob-00** [comment]
> Hi @tob-00 do you have to unplug and plug back in the charger whenever you do battery charging off in the terminal?

No I don't but it takes some time. I think after like every percentage charged it is evaluated if charging should be continued and then it is turned off...

**Comment by actuallymentor** [comment]
I edited the setup script. It should now work by running:

```
curl -s https://raw.githubusercontent.com/actuallymentor/battery/main/setup.sh | bash
```
