### ISSUE TITLE
M2 Macs?

### ISSUE THREAD

**Issue by PTTRN5** [actuallymentor/battery#42]
Does this work for all Apple silicon Macs? Can I use it on Macbook Air M2?

**Comment by la1440** [comment]
I don't see why not, in theory the only limitation should be translating from x86_64 to arm64 which between M1 and M2 is not an issue as both use arm64. Do please try it and let us all know if it works!

**Comment by dannykorpan** [comment]
Works without any problems on my MacBook Air M2.
