### ISSUE TITLE
The battery level setting is preserved, but it still charges until I run battery again

### ISSUE THREAD

**Issue by ballo** [actuallymentor/battery#44]
**What is the issue? (required)**
If I reboot (or some other reset situation?) the battery status shows the level of the battery to be maintained has been preserved, but the charging is enabled even if the battery level is much higher until I run battery maintain. 

**What exactly did you do to produce the issue? (required)**
1. sudo battery maintain 40
2. reboot
3. sudo battery status
5. See "Your battery is currently being maintained at 40%" which is correct (battery level preserved) but also nonsensically see "smc charging enabled"
6. sudo battery maintain 40
7. sudo battery status
8. See "Your battery is currently being maintained at 40%" but also "smc charging disabled" which is obviously what I want

**Expected behavior (required)**
If the battery level is above what the maintenance level is, charging should be disabled. 

**Screenshots (optional)**
<img width="682" alt="Screen Shot 2023-01-21 at 10 51 37 PM" src="https://user-images.githubusercontent.com/631311/213902639-a5d6f49e-44d4-46fd-9a2a-e5abfad06836.png">

**Comment by ballo** [comment]
BTW this is on a 8 core m1 13" macbook pro

**Comment by ballo** [comment]
Sigh, it reset this time and I didn't even reboot. Back on 100%.

I constantly have to babysit this thing. I might have to create a cron job to periodically check the battery level to detect when this is malfunctioning

**Comment by actuallymentor** [comment]
Can you show me the output of `battery logs` before you reboot and after? It would really help in debugging.

**Comment by ballo** [comment]
I've never seen battery logs show any output

**Comment by ballo** [comment]
<img width="299" alt="Screen Shot 2023-03-14 at 11 31 20 AM" src="https://user-images.githubusercontent.com/631311/225103499-45185cea-64e4-4f14-ba45-cb51d90c00d6.png">
It happened again. I think this time because I had to reboot
