### ISSUE TITLE
Thoughts on being able to change the battery ceiling to a non-80% value?

### ISSUE THREAD

**Issue by la1440** [actuallymentor/battery#45]
Some people like to use their MacBooks as desktops, and for those types of people an option to further decrease the limit to 50-60% might not be a bad idea. Others frequently keep it plugged in but also travel a lot with it, so for those types a 70% limit may make more sense. Thoughts on implementing the aforementioned functionality? (As it stands, _battery_ can only set the limit to 80%)

**Comment by dsempel** [comment]
This tool already has that functionality, but the docs state:

> Also automatically installs the battery command line tool. If you want a custom charging percentage, the CLI is the only way to do that.

You can do it like this: `battery maintain 50`
