### ISSUE TITLE
"Charging off" mode does not work

### ISSUE THREAD

**Issue by Zeroscl** [actuallymentor/battery#46]
Hello, I installed Battery from the Brew repository, I followed all the instructions successfully, but when I try to turn off my laptop's battery charge autonomously it turns back on, and when I let it discharge almost completely when connecting it reloads to 100%. I'm using a MB Pro M1 with Big Sur 11.7.3

![SCR-20230126-quf](https://user-images.githubusercontent.com/87509060/214964236-aa1bdd37-0817-43c5-8de9-bd1e9c7afe35.png)

**Comment by Zeroscl** [comment]
Could that be related to clamshell mode? I mean when the MB Pro is closed and I have it connected to an external monitor? Since when I tried al dente I had that mode disabled for the free mode that did not disconnect the battery charge.  Thanks !!!

**Comment by romanvazquez** [comment]
Me parece que es porque ya tienes la batería completamente cargada y por ello el comando "battery charging off" no funciona. Si tu batería estuviera en 99 o menos entonces sí se suspende la carga.

**Comment by Zeroscl** [comment]
Deje caer la carga de la bateria hasta el 70%, reinstale la app de battery y active el MAINTAIN al 80% y el CHARGE al 80%.  Veamos si funciona ahora.  

Saludos

Drop the battery charge down to 70%, reinstall the battery app and activate MAINTAIN at 80% and CHARGE at 80%. Let's see if it works now. 

Regards

**Comment by actuallymentor** [comment]
Did that fix it @Zeroscl ?
