### ISSUE TITLE
[Feature Request] Improve Menu GUI information

### ISSUE THREAD

**Issue by NdR91** [actuallymentor/battery#47]
**Is your feature request related to a problem? Please describe.**
The GUI menu only shows a standard set of options:

- Enable 80% Limit;
- Disable 80% Limit;

<img width="224" alt="image" src="https://user-images.githubusercontent.com/52299148/215496267-ca4be381-9850-4cad-bc07-4cf1b602a505.png">

**Describe the solution you'd like**
Let the Top bar menu show the setup done in the CLI.
For example the informations I get with the `battery status`command

A nice set of information to be displayed in that menu is:

- Mantain percentage set;
- Charging Enabled/Disabled;
- Battery charging YES or NOT;

**Describe alternatives you've considered**
The alternative is to get those info inside the terminal. Not properly comfortable.

**Comment by met97** [comment]
+1

**Comment by Zeroscl** [comment]
+1

**Comment by ballo** [comment]
I don't even use the menu. Maybe fix the basic functionality of the program first so it doesn't keep charging past the selected level.

**Comment by NdR91** [comment]
> I don't even use the menu. Maybe fix the basic functionality of the program first so it doesn't keep charging past the selected level.

This comment actually don't contribute on this issue. 
Open a new one (or +1 an existing one) if you need some bug fix.

**Comment by JacksonChen666** [comment]
@actuallymentor Keywords to close an issue does not function in GitHub releases. It is meant to be used in commit messages.

**Comment by actuallymentor** [comment]
@JacksonChen666 I see you're very on top of things, thanks ;)

**Comment by NdR91** [comment]
> @JacksonChen666 I see you're very on top of things, thanks ;)

Really thank you for your work!
