### ISSUE TITLE
Impossible to install the dmg on M1 pro 14"

### ISSUE THREAD

**Issue by LucasMSalgado** [actuallymentor/battery#51]
**What is the issue? (required)**
Impossible to install the battery software using the option with the dmg file.

**What exactly did you do to produce the issue? (required)**
After copying the dmg to the application folder,
Launching the dmg for the installation leads to multiples errors :
<img width="301" alt="Capture d’écran 2023-02-05 à 17 22 33" src="https://user-images.githubusercontent.com/124517464/216831437-660003d7-5469-4b15-8ea9-6dbb60da3e59.png">
<img width="297" alt="Capture d’écran 2023-02-05 à 17 22 55" src="https://user-images.githubusercontent.com/124517464/216831439-a4c92ec5-a141-48f4-abb6-d5248067403d.png">
<img width="295" alt="Capture d’écran 2023-02-05 à 17 23 08" src="https://user-images.githubusercontent.com/124517464/216831440-3839dd26-e2bd-4508-8d57-e695f173cab5.png">
<img width="299" alt="Capture d’écran 2023-02-05 à 17 23 16" src="https://user-images.githubusercontent.com/124517464/216831441-8a67cd41-5655-45b3-bb34-6d55aa781526.png">

Then the installation finished and the icon is on the top bar and on the application list, but it is impossible to launch it or setup it.
<img width="606" alt="Capture d’écran 2023-02-05 à 17 23 34" src="https://user-images.githubusercontent.com/124517464/216831557-685d9cb8-f078-4765-b44c-6e1a2ccf9693.png">

**Expected behavior (required)**
I expected has explained in the tutorial to be able to acces to the menu on the top bar and be able to launch the application.

**Additional context (optional)**
Thanks you a lot for your soft, the dmg file make it very more user friendly.

Respectfully,
Lucas

**Comment by st-ivan** [comment]
hi, just updated to 1.06, same issues here. 
1.05 works fine.. no discharge functionality tho.

**Comment by NdR91** [comment]
I was creating the same issue, then I saw this one.

Same errors with this dmg

**Comment by st-ivan** [comment]
ok, i uninstalled 1.06, reainstalled 1.05, disabled limit, uninstalled 1.05, installed and reinstalled 1.06 and it now works. but im not getting same info as in the scrennshot.. heres what i got:

<img width="300" alt="image" src="https://user-images.githubusercontent.com/30345865/216833275-7ae62f35-f857-4f11-99b3-fa72f059b8c3.png">

**Comment by NdR91** [comment]
Ok I found a similar workaround. 

Disabling the battery limit, you can quit the application and overwrite the 1.0.6 release on the 1.0.5. Prior to this I updated the CLI version.



> ok, i uninstalled 1.06, reainstalled 1.05, disabled limit, uninstalled 1.05, installed and reinstalled 1.06 and it now works. but im not getting same info as in the scrennshot.. heres what i got:
> 
> <img alt="image" width="300" src="https://user-images.githubusercontent.com/30345865/216833275-7ae62f35-f857-4f11-99b3-fa72f059b8c3.png">
> 
> m1pro 14 im going back to 1.05 until 1.06 is fixed.

Regarding this, do you also set the `battery discharge` setting?
If not it won't discharge if you plug the power over that percentage.

**Comment by actuallymentor** [comment]
@LucasMSalgado tjabks for letting me know. Can you show me the output of `battery logs`?

**Comment by actuallymentor** [comment]
Found the issue. Foolish me. With I knew more about automated testing for mac apps...

Will push a fix within a few hours

**Comment by actuallymentor** [comment]
Ok, so because I am a terrible person I have replaced the release dmg with the fixed one without incrementing the version number. Can you download it and verify if works for you?

**Comment by NdR91** [comment]
> Ok, so because I am a terrible person I have replaced the release dmg with the fixed one without incrementing the version number. Can you download it and verify if works for you?

Installation went well with this dmg.

FYI: the update overwrites the preferences.
My "maintain" option is set on 75%.

After the update:
```
╭─ndr@NdRs-MBP.local /  
╰─➤  battery status
02/05/23-20:08:15 - Battery at 76% (attached; remaining), smc charging enabled
02/05/23-20:08:15 - Your battery is currently being maintained at 80%
```

<img width="291" alt="image" src="https://user-images.githubusercontent.com/52299148/216839713-9f050e6b-b740-4353-bcdc-fe1964a8e8b6.png">


Note a but issue, but maybe you want to know it.

**Comment by actuallymentor** [comment]
The GUI only supports 80%, though in this new version if you run the cli at 75, the GUI will show 75 (but will default back to 80 when you disable).

The GUI is mostly for normies, the cli for custom stuff.
