### ISSUE TITLE
Version 1.0.5 doesn't update to 1.0.6 [Homebrew]

### ISSUE THREAD

**Issue by NdR91** [actuallymentor/battery#52]
**What is the issue? (required)**
Homebrew installation doesn't find the new version (1.0.6)

**What exactly did you do to produce the issue? (required)**
With the `battery update` command it keeps the 1.0.5 version

```
This will run curl -sS https://raw.githubusercontent.com/actuallymentor/battery/main/update.sh | bash
Press any key to continue

🔋 Starting battery update

[ 1/3 ] Cloning battery repository
[ 2/3 ] Writing script to /usr/local/bin/battery
[ 3/3 ] Removed temporary folder

🎉 Battery tool updated.
```

**Screenshots (optional)**
<img width="227" alt="image" src="https://user-images.githubusercontent.com/52299148/216833484-2fcb1b1c-58a7-4c2b-8446-d1c9e4139819.png">

**Comment by NdR91** [comment]
I just found out that homebrew updates doesn't include the GUI version. So I sill have to install it via DMG, right?

**Comment by actuallymentor** [comment]
To update the home brew version takes a day or so. Whenever I update the app I need to open a pull request with them, and they are very diligent about checking them.

**Comment by NdR91** [comment]
> To update the home brew version takes a day or so. Whenever I update the app I need to open a pull request with them, and they are very diligent about checking them.

Oh ok! Thanks for the feedback
