### ISSUE TITLE
Status bar icon not following theme color

### ISSUE THREAD

**Issue by waterlou** [actuallymentor/battery#54]
The status bar icon is always in black color even in light theme.

<img width="254" alt="Screenshot 2023-02-08 at 11 20 21 PM" src="https://user-images.githubusercontent.com/68549/217572499-f0c97247-5cc8-4633-9267-69c5177fbec2.png">

**Comment by actuallymentor** [comment]
When you hover the icon, does it change?

**Comment by actuallymentor** [comment]
Found a solution, will include in release `1.0.7`

**Comment by abstractrealism** [comment]
Just installed 1.0.7 and this behavior is still present. I had thought it was by design.
