### ISSUE TITLE
cli works fine, but app cannot initialize

### ISSUE THREAD

**Issue by sataset** [actuallymentor/battery#6]
I have uninstalled battery cli tool and installed app instead:
<img width="328" alt="image" src="https://user-images.githubusercontent.com/28687456/191739434-72645a8c-268b-4e9b-87d1-d986c91ff019.png">

after installing cli tool back again and restarting app:
<img width="372" alt="image" src="https://user-images.githubusercontent.com/28687456/191739752-f82f890a-1610-4739-8f7f-eb58f03c9cd5.png">

if I am trying to maintain 80 level from app:
<img width="328" alt="image" src="https://user-images.githubusercontent.com/28687456/191739859-3ee9650a-9392-4801-8f1d-cf705b6469b2.png">

**Comment by actuallymentor** [comment]
Thanks for the report! The app is still in beta and has some bugs...

Could you run `sudo rm -rf ~/.battery` and reinstall the newest app version? It should work now.

**Comment by sataset** [comment]
did `sudo battery uninstall` and reinstalled app to the latest version

same issue, but I received the message you added in the latest commit saying that CLI utility installed successfully

**Comment by sataset** [comment]
oh wait, cleaning up `~/.battery` directory helped

can you add cleaning up to the install script for the application? or maybe add some logic to backup / split CLI configs?

**Comment by actuallymentor** [comment]
Hey @sataset! The new versions should fix this. You can now also install the app through `brew install battery`.
