### ISSUE TITLE
uninstallment guide

### ISSUE THREAD

**Issue by TheGlorySaint** [actuallymentor/battery#66]
**What is the issue? (required)**
I'd like to see in the ReadMe a Guide how to completely uninstall battery and all its component and also the command line tool. What also could be possible, an uninstallation function inside battery itself.

**Expected behavior (required)**
A guide or uninstall button that uninstalls battery and its components.

Update:

Please verify if I have uninstalled every related battery components and the app itself.
I have run these both commands in my terminal.

brew uninstall battery
battery uninstall

**Comment by actuallymentor** [comment]
`brew uninstall battery` should uninstall also components if you installed through brew. Please re-open if you find any lingering app files so I can investigate.

**Comment by TheGlorySaint** [comment]
When I uninstalled battery with `brew uninstall battery` I still could use the battery command in my Terminal. After running `battery uninstall` when I wasn't able to run that command anymore.

**Comment by actuallymentor** [comment]
There is now a GUI uninstall button, as well as a more complete command line uninstall. Thanks for reporting!
