### ISSUE TITLE
Install not working - Version 1.08

### ISSUE THREAD

**Issue by martin-77** [actuallymentor/battery#67]
**What is the issue? (required)**
Install not working or not starting correctly 

**What exactly did you do to produce the issue? (required)**
1. install with brew install 
2. Following Error appear:

Battery limiter error: Command failed: PATH=$PATH:/bin:/usr/bin:/usr/local/bin:/usr/sbin:/opt/homebrew:/usr/bin/ battery status_csv
/bin/bash: battery: command not found

Command failed: PATH=$PATH:/bin:/usr/bin:/usr/local/bin:/usr/sbin:/opt/homebrew:/usr/bin/ battery maintain 80
/bin/bash: battery: command not found

Battery limiter error: Command failed: PATH=$PATH:/bin:/usr/bin:/usr/local/bin:/usr/sbin:/opt/homebrew:/usr/bin/ battery status_csv
/bin/bash: battery: command not found

**Expected behavior (required)**
working install

**Error logs**
Battery limiter error: Command failed: PATH=$PATH:/bin:/usr/bin:/usr/local/bin:/usr/sbin:/opt/homebrew:/usr/bin/ battery status_csv
/bin/bash: battery: command not found

Command failed: PATH=$PATH:/bin:/usr/bin:/usr/local/bin:/usr/sbin:/opt/homebrew:/usr/bin/ battery maintain 80
/bin/bash: battery: command not found

Battery limiter error: Command failed: PATH=$PATH:/bin:/usr/bin:/usr/local/bin:/usr/sbin:/opt/homebrew:/usr/bin/ battery status_csv
/bin/bash: battery: command not found

No idea how to solve this.
Macbook Pro M1 Max - Ventura 13.2

**Comment by hermannrh88** [comment]
Same issue.

**Comment by vertumnuss** [comment]
Same here MB Pro M1 Max - Ventura 13.2.1

**Comment by Neifab** [comment]
Hello, same here, MBP M2 Max, Ventura 13.2.1

**Comment by actuallymentor** [comment]
@martin-77 please use the issue template so I have debugging info.

**Comment by martin-77** [comment]
I think i was using the Template. 
Pleased tell me, what exactly you do you need?
