### ISSUE TITLE
does not work after installation

### ISSUE THREAD

**Issue by counterpointer** [actuallymentor/battery#70]
I installed 1.0.8 with dmg.
Installation completed but after entering admin password I had 3 error messages.

> Executing PATH=$PATH:/bin:/usr/bin:/usr/local/bin:/usr/sbin:/opt/homebrew:/usr/bin/ battery status_csv
> Error getting battery status: 
> Error: Command failed: PATH=$PATH:/bin:/usr/bin:/usr/local/bin:/usr/sbin:/opt/homebrew:/usr/bin/ battery status_csv
> /bin/bash: battery: command not found
> 
> Executing PATH=$PATH:/bin:/usr/bin:/usr/local/bin:/usr/sbin:/opt/homebrew:/usr/bin/ battery maintain 80
> Error enabling battery: 
> Error: Command failed: PATH=$PATH:/bin:/usr/bin:/usr/local/bin:/usr/sbin:/opt/homebrew:/usr/bin/ battery maintain 80
> /bin/bash: battery: command not found
> 
> Refreshing tray icon...
> Executing PATH=$PATH:/bin:/usr/bin:/usr/local/bin:/usr/sbin:/opt/homebrew:/usr/bin/ battery status_csv
> Error getting battery status: 
> Error: Command failed: PATH=$PATH:/bin:/usr/bin:/usr/local/bin:/usr/sbin:/opt/homebrew:/usr/bin/ battery status_csv
> /bin/bash: battery: command not found

I can't quit the app nor uninstall it

**Comment by Neifab** [comment]
Had the same, but no problems with Homebrew install.

**Comment by counterpointer** [comment]
Yes, it works. Thanks!
I had not Homebrew installed, so it takes time.

**Comment by galaxydpw** [comment]
installed via homebrew, and same issue.

![image](https://user-images.githubusercontent.com/59457444/219700654-f0d723ed-7067-4ef5-9696-76eb95126268.png)
