### ISSUE TITLE
Battery limiter error

### ISSUE THREAD

**Issue by mwennrich81** [actuallymentor/battery#74]
**What is the issue? (required)**

Battery limiter error: Command failed: PATH=$PATH:/bin:/usr/bin:/usr/local/bin:/usr/sbin:/opt/homebrew:/usr/bin/ battery status_csv
/bin/bash: battery: command not found

**What exactly did you do to produce the issue? (required)**

Directly after the installation 

**Expected behavior (required)**

**Screenshots (optional)**

![Bildschirm­foto 2023-02-15 um 10 20 45](https://user-images.githubusercontent.com/57907257/218986297-126655ad-cf16-44f0-8d25-02972710dc75.png)

**Additional context (optional)**

**Comment by PeterPung** [comment]
Got exactly same problem after installed 1.1.4

**Comment by actuallymentor** [comment]
@PeterPung would you mind resubmitting this with the issue template (which I created only after your issue)? It has the debugging steps I need :)
