### ISSUE TITLE
Error displayed straight after installation

### ISSUE THREAD

**Issue by amauryhubault** [actuallymentor/battery#76]
After asking for my password, I have this error displayed immediately:

Battery limiter error: Command failed: PATH=$PATH:/bin:/usr/bin:/usr/local/bin:/usr/sbin:/opt/homebrew:/usr/bin/ battery status_csv
/bin/bash: battery: command not found

I assume it's not very precise, anything I can do to troubleshoot?

**Comment by earthsound** [comment]
@amauryhubault as a workaround, you could try installing with homebrew. See [this comment](https://github.com/actuallymentor/battery/issues/70#issuecomment-1430599336) in #70.

**Comment by amauryhubault** [comment]
Same issue indeed
