### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by mumu38** [actuallymentor/battery#79]
**What is the issue? (required)**

**What exactly did you do to produce the issue? (required)**

**Expected behavior (required)**

**Screenshots (optional)**
If applicable, add screenshots to help explain your problem. On a Mac you can click `control`+`command`+`shift`+`4` to create a screenshot that you can paste into this field with `command`+`4`.

**Error logs**
If you know how a terminal works, please paste the content of `battery logs` here. This allows me to see potential errors on your device.

**Additional context (optional)**

**Comment by mumu38** [comment]
Hi,
I tried to install the 1.0.8 version on a MacBook Pro M1 with Monterey.
I got the following errors during the update process after launching the app:

<img width="416" alt="Capture d’écran 2023-02-16 à 17 57 24" src="https://user-images.githubusercontent.com/47277713/219436083-2bac5312-b32b-4467-bfea-bfc55e49f1d5.png">
<img width="416" alt="Capture d’écran 2023-02-16 à 17 57 38" src="https://user-images.githubusercontent.com/47277713/219436099-e51a8888-c612-4486-bcab-903490642ef8.png">
<img width="416" alt="Capture d’écran 2023-02-16 à 17 57 32" src="https://user-images.githubusercontent.com/47277713/219436109-1ef7c79b-c410-4f04-9239-869137c728f3.png">

Is there something I missed? 

Thanks

**Comment by earthsound** [comment]
duplicate of #74

**Comment by mumu38** [comment]
OK. Just needed to install command tools.
Didn't even know those existed, even less installing them was needed.
Thanks
