### ISSUE TITLE
How to disable telemetry?

### ISSUE THREAD

**Issue by sunknudsen** [actuallymentor/battery#82]
Hey @actuallymentor, thanks for developing battery.

Noticed Little Snitch in app screenshots… was surprised when I noticed battery was calling icanhasip.com and unidentifiedanalytics.web.app.

How can one disable telemetry?

**Comment by actuallymentor** [comment]
Hey!

Nice catch, TL;DR: you cannot, but a pull-request for the option is welcome, and you can block most safely. Though I recommend just blocking the analytics.

I added a section to the readme:

---

This tool calls a number of urls, blocking all of them will only break auto-updates.

1. `unidentifiedanalytics.web.app` is a self-made app that tracks app installations, I use it to see if enough people use the app to justify spending time on it.
1. `icanhasip.com` is used to see if there is an internet connection
1. `github.com` is used both as a liveness check and as the source of updates for the underlying command-line utility
1. `electronjs.org` hosts the update server for the GUI

All urls are called over `https` and so not leak data. Unidentified Analytics keeps track of unique ip addresses that open the app, but nothing else.
