### ISSUE TITLE
battery command stopped working

### ISSUE THREAD

**Issue by ballo** [actuallymentor/battery#83]
**What is the issue? (required)**
After doing a brew upgrade, the command fails to work. It claims to be maintaining the battery level but isn't charging. Also, new error?
**What exactly did you do to produce the issue? (required)**
 > sudo battery maintain 40
01:16:11 - Starting battery maintenance at 40%
01:16:11 - Maintaining battery at 40%
(does not maintain at 40%)
 > sudo battery status
/usr/local/bin/battery: line 107: smc: command not found
01:16:22 - Battery at 27% (attached; remaining), smc charging disabled
01:16:22 - Your battery is currently being maintained at 40%
(smc command not found)
**Screenshots (optional)**

<img width="346" alt="Screen Shot 2023-02-21 at 1 19 27 AM" src="https://user-images.githubusercontent.com/631311/220287577-61b8eb34-0836-4efb-8bda-731ebaba6f8e.png">

**Error logs**
> battery logs 
results in null output.

**Comment by ballo** [comment]
M1 MaBook Pro 13"

**Comment by actuallymentor** [comment]
You should never call `battery` with sudo. Please `battery uninstall` and reinstall.

Before reinstall please make sure you removed any artifacts that exist because you were using `sudo`:

```
sudo rm -rf ~/.battery
binfolder=/usr/local/bin
sudo rm -v "$binfolder/smc" "$binfolder/battery"
```

**Comment by ballo** [comment]
OK, I uninstalled battery and the other stuff, and after a brew install battery:
> battery charge 40
zsh: command not found: battery

**Comment by actuallymentor** [comment]
If you want the CLI: you need to open the GUI at least once or run the CLI-only script in the readme.

**Comment by ballo** [comment]
Still broken 
<img width="301" alt="Screen Shot 2023-02-24 at 2 56 25 PM" src="https://user-images.githubusercontent.com/631311/221300838-54276e90-b32e-4033-baf7-7f6c639c147a.png">
<img width="563" alt="Screen Shot 2023-02-24 at 2 56 40 PM" src="https://user-images.githubusercontent.com/631311/221300896-16f10ffb-167d-482e-b356-81caa1be07cd.png">

**Comment by ballo** [comment]
Why close this ticket when it's clearly still broken?
