### ISSUE TITLE
Regarding runing battery script or scheduled task with lid closed or sleep mode

### ISSUE THREAD

**Issue by HeroLink** [actuallymentor/battery#88]
Basically, I want to run the battery script with lid of my MabBook closed. Specifically, I run `battery maintain 80` before I go sleeping. After closing the lid, I would like `battery charge 100` can be ran 10 minutes before I wake up.

I have tried `pmset` to wake up my MacBook in advance and scheduled a`crontab` task to run the charging script after 1 minute. For example, I wake up at 8:30 AM on Tuesday. For waking up my MacBook, I use `sudo pmset repeat wake T 07:30:00`. For charging, I use `31 7 * * 2 battery charge 100` in `crontab`.

But it does not work and the script will be ran after I open the lid. Is there any way that I can run the script with the lid closed?

**Comment by actuallymentor** [comment]
I'm afraid this is a scripting question beyond the scope of this app. The only thing I can say is that the app should work with the lid closed (it does for me) and a cron should be sufficient in the morning.
