### ISSUE TITLE
Permission error on startup

### ISSUE THREAD

**Issue by EzeGmnz** [actuallymentor/battery#93]
**What is the issue? (required)**
Running on M1 pro, battery version: [1.0.10](https://github.com/actuallymentor/battery/releases/tag/v1.0.10) & [1.1.0-beta](https://github.com/actuallymentor/battery/releases/tag/v1.1.0-beta)
After opening the battery app it shows the following icon
<img width="112" alt="image" src="https://user-images.githubusercontent.com/40328394/221928308-c2cd1fca-5221-4c6f-8aa3-b74591316d56.png">
it installs the required components successfully and after ~5secs I get the following error
<img width="271" alt="image" src="https://user-images.githubusercontent.com/40328394/221928510-bff70bc1-0606-455a-8e8c-e9b32f613236.png">

and the battery icons remains greyed out 
<img width="49" alt="image" src="https://user-images.githubusercontent.com/40328394/221928588-7f46c7e5-9f35-4c99-861a-a1d469cd4817.png">

**Error logs**
```

🎉 Battery tool installed. Type "battery help" for instructions.

Executing nohup curl "https://unidentifiedanalytics.web.app/touch/?namespace=battery" > /dev/null 2>&1
App initialisation process complete
Executing PATH=$PATH:/bin:/usr/bin:/usr/local/bin:/usr/sbin:/opt/homebrew:/usr/bin/ battery status_csv
Executing PATH=$PATH:/bin:/usr/bin:/usr/local/bin:/usr/sbin:/opt/homebrew:/usr/bin/ battery maintain 80
Error getting battery status: 
/usr/local/bin/battery: line 149: /usr/local/bin/smc: Permission denied
/usr/local/bin/battery: line 158: /usr/local/bin/smc: Permission denied

Executing PATH=$PATH:/bin:/usr/bin:/usr/local/bin:/usr/sbin:/opt/homebrew:/usr/bin/ battery status_csv
Refreshing tray icon...
enable_battery_limiter exec complete
Error getting battery status: 
/usr/local/bin/battery: line 149: /usr/local/bin/smc: Permission denied
/usr/local/bin/battery: line 158: /usr/local/bin/smc: Permission denied

Error generating menu: 
TypeError: Cannot destructure property 'battery_state' of '(intermediate value)' as it is undefined.

```

**Comment by ioExpander** [comment]
Hi. I'm getting the same error on an M1 Macbook Air.

**Comment by actuallymentor** [comment]
I think this should be fixed now, can you try to run `battery uninstall` in the terminal and then run the GUI app again?

**Comment by thomasboleyn** [comment]
> I think this should be fixed now, can you try to run `battery uninstall` in the terminal and then run the GUI app again?

Thanks, works like a charm now.

**Comment by EzeGmnz** [comment]
> I think this should be fixed now, can you try to run `battery uninstall` in the terminal and then run the GUI app again?

Worked, thanks!
