### ISSUE TITLE
Update Homebrew battery.rb

### ISSUE THREAD

**Issue by kevinm6** [actuallymentor/battery#97]
**What is the issue? (required)**
It’s impossible update the app from homebrew, since the url is not valid anymore.

**What exactly did you do to produce the issue? (required)**
`brew upgrade —-cask battery`

**Expected behavior (required)**
Just update to last release.

**Additional context (optional)**
As reported in this [issue](https://github.com/Homebrew/homebrew-cask/pull/140721#issuecomment-1456751763) the url has changed.
Is impossible even use `brew bump-cask-pr battery —-version=“<last_version>` cause the url is not valid (due to renaming files adding **mac** : `battery-#{version}-mac-arm64.dmg`

**Comment by kevinm6** [comment]
I’ve already provide a **PR** to `homebrew-casks` to fix this.

**Comment by actuallymentor** [comment]
Thank you!
